function [p1,p2,dp1,dp2] = autoGen_acrobotKinematics(q1,q2,dq1,dq2,l1,l2)
%AUTOGEN_ACROBOTKINEMATICS
%    [P1,P2,DP1,DP2] = AUTOGEN_ACROBOTKINEMATICS(Q1,Q2,DQ1,DQ2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    11-Jul-2015 20:41:45

t2 = sin(q1);
t3 = l1.*t2;
t4 = cos(q1);
p1 = [t3;-l1.*t4];
if nargout > 1
    t5 = dq1.*l1.*t4;
    t6 = cos(q2);
    t7 = dq1.*l1.*t2;
    t8 = sin(q2);
    p2 = [t3+l2.*t8;-l1.*t4-l2.*t6];
end
if nargout > 2
    dp1 = [t5;t7];
end
if nargout > 3
    dp2 = [t5+dq2.*l2.*t6;t7+dq2.*l2.*t8];
end
