function [p1,p2,dp1,dp2] = autoGen_kinematics(q1,q2,dq1,dq2,l)
%AUTOGEN_KINEMATICS
%    [P1,P2,DP1,DP2] = AUTOGEN_KINEMATICS(Q1,Q2,DQ1,DQ2,L)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    17-Jun-2015 22:13:36

t2 = sin(q1);
t3 = l.*t2;
t4 = cos(q1);
p1 = [t3;-l.*t4];
if nargout > 1
    t5 = dq1.*l.*t4;
    t6 = cos(q2);
    t7 = dq1.*l.*t2;
    t8 = sin(q2);
    p2 = [t3+l.*t8;-l.*t4-l.*t6];
end
if nargout > 2
    dp1 = [t5;t7];
end
if nargout > 3
    dp2 = [t5+dq2.*l.*t6;t7+dq2.*l.*t8];
end
