function [ddq1,ddq2] = autoGen_dynamics(q1,q2,dq1,dq2,u,m1,m2,g,l1,l2)
%AUTOGEN_DYNAMICS
%    [DDQ1,DDQ2] = AUTOGEN_DYNAMICS(Q1,Q2,DQ1,DQ2,U,M1,M2,G,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    16-Jun-2015 22:50:03

t2 = q1.*2.0;
t6 = q2.*2.0;
t3 = t2-t6;
t4 = q1-q2;
t5 = sin(q1);
t7 = m1.*2.0;
t8 = cos(t3);
t9 = m2+t7-m2.*t8;
t10 = 1.0./t9;
t11 = cos(t4);
t12 = dq1.^2;
t13 = l1.^2;
t14 = sin(t4);
t15 = m2.^2;
t16 = dq2.^2;
t17 = l2.^2;
t18 = sin(t3);
ddq1 = -(1.0./l1.^2.*t10.*(l2.*u.*2.0+l1.*t11.*u.*2.0+g.*l1.*l2.*m2.*sin(q1-t6)+g.*l1.*l2.*m1.*t5.*2.0+g.*l1.*l2.*m2.*t5+l2.*m2.*t12.*t13.*t18+l1.*m2.*t14.*t16.*t17.*2.0))./l2;
if nargout > 1
    t19 = sin(q2);
    t20 = -q2+t2;
    t21 = sin(t20);
    ddq2 = (1.0./l2.^2.*t10.*(l1.*m1.*u.*2.0+l1.*m2.*u.*2.0+l2.*m2.*t11.*u.*2.0-g.*l1.*l2.*t15.*t19+g.*l1.*l2.*t15.*t21+l2.*t12.*t13.*t14.*t15.*2.0+l1.*t15.*t16.*t17.*t18+l2.*m1.*m2.*t12.*t13.*t14.*2.0-g.*l1.*l2.*m1.*m2.*t19+g.*l1.*l2.*m1.*m2.*t21))./(l1.*m2);
end
