function [p1,p2,dp1,dp2] = autoGen_kinematics(q1,q2,dq1,dq2,d,l)
%AUTOGEN_KINEMATICS
%    [P1,P2,DP1,DP2] = AUTOGEN_KINEMATICS(Q1,Q2,DQ1,DQ2,D,L)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    18-Jun-2015 12:29:42

t2 = sin(q1);
t3 = cos(q1);
t4 = l.*t2;
t5 = d.*t3;
t6 = t5-l.*t3;
p1 = [t4-d.*t2;t6];
if nargout > 1
    t7 = cos(q2);
    t8 = sin(q2);
    p2 = [t4+d.*t8;-d.*t7-l.*t3];
end
if nargout > 2
    dp1 = [-dq1.*t6;dq1.*(t4-d.*t2)];
end
if nargout > 3
    dp2 = [d.*dq2.*t7+dq1.*l.*t3;d.*dq2.*t8+dq1.*l.*t2];
end
