function [ddq1,ddq2] = autoGen_dynamics(q1,q2,dq1,dq2,u,m1,m2,g,l)
%AUTOGEN_DYNAMICS
%    [DDQ1,DDQ2] = AUTOGEN_DYNAMICS(Q1,Q2,DQ1,DQ2,U,M1,M2,G,L)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    17-Jun-2015 22:13:35

t2 = q1-q2;
t3 = sin(q1);
t4 = l.^2;
t5 = q1.*2.0;
t7 = q2.*2.0;
t6 = t5-t7;
t8 = 1.0./l.^2;
t9 = m1.*2.0;
t10 = cos(t6);
t11 = m2+t9-m2.*t10;
t12 = 1.0./t11;
t13 = cos(t2);
t14 = dq2.^2;
t15 = sin(t6);
t16 = m2.^2;
t17 = dq1.^2;
t18 = sin(t2);
ddq1 = -t8.*t12.*(u.*2.0+t13.*u.*2.0+g.*l.*m1.*t3.*2.0+g.*l.*m2.*t3+m2.*t4.*t14.*t18.*2.0+m2.*t4.*t15.*t17+g.*l.*m2.*sin(q1-t7));
if nargout > 1
    t19 = -q2+t5;
    t20 = sin(t19);
    t21 = sin(q2);
    ddq2 = (t8.*t12.*(m1.*u.*2.0+m2.*u.*2.0+m2.*t13.*u.*2.0+g.*l.*t16.*t20-g.*l.*t16.*t21+t4.*t14.*t15.*t16+t4.*t16.*t17.*t18.*2.0+g.*l.*m1.*m2.*t20-g.*l.*m1.*m2.*t21+m1.*m2.*t4.*t17.*t18.*2.0))./m2;
end
