function [q1New,q2New,dq1New,dq2New] = autoGen_heelStrike(q1,q2,dq1,m1,m2)
%AUTOGEN_HEELSTRIKE
%    [Q1NEW,Q2NEW,DQ1NEW,DQ2NEW] = AUTOGEN_HEELSTRIKE(Q1,Q2,DQ1,M1,M2)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    17-Jun-2015 22:13:37

q1New = q2;
if nargout > 1
    q2New = q1;
end
if nargout > 2
    t2 = q1.*2.0;
    t6 = q2.*2.0;
    t3 = t2-t6;
    t4 = cos(t3);
    t5 = m1.*2.0;
    t7 = m2+t5-m2.*t4;
    t8 = 1.0./t7;
    dq1New = dq1.*m1.*t8.*cos(q1-q2).*-2.0;
end
if nargout > 3
    dq2New = dq1.*m1.*t8.*(t4+1.0);
end
