function [q1New,q2New,dq1New,dq2New] = autoGen_heelStrike(q1,q2,dq1,dq2,m,I,d,l)
%AUTOGEN_HEELSTRIKE
%    [Q1NEW,Q2NEW,DQ1NEW,DQ2NEW] = AUTOGEN_HEELSTRIKE(Q1,Q2,DQ1,DQ2,M,I,D,L)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    18-Jun-2015 12:29:54

q1New = q2;
if nargout > 1
    q2New = q1;
end
if nargout > 2
    t2 = d.^2;
    t3 = l.^2;
    t4 = m.^2;
    t5 = q1-q2;
    t6 = cos(t5);
    t7 = 1.0./d;
    t8 = 1.0./m;
    t9 = I.*d.*2.0;
    t10 = d.*m.*t2.*2.0;
    t11 = d.*m.*t3.*3.0;
    t12 = q1.*2.0;
    t20 = q2.*2.0;
    t13 = t12-t20;
    t14 = cos(t13);
    t15 = t9+t10+t11-I.*l.*t6.*2.0-l.*m.*t2.*4.0-d.*m.*t3.*t14;
    t16 = 1.0./t15;
    t17 = I.^2;
    t18 = dq1.*t17;
    t19 = t2.^2;
    dq1New = t7.*t8.*t16.*(t18-dq2.*t4.*t19+I.*dq1.*m.*t2-I.*dq2.*m.*t2-I.*d.*dq1.*l.*m+d.*dq2.*l.*t2.*t4+dq1.*t2.*t3.*t4.*t6+I.*d.*dq1.*l.*m.*t6-d.*dq1.*l.*t2.*t4.*t6).*-2.0;
end
if nargout > 3
    dq2New = t7.*t8.*t16.*(t18+dq1.*t4.*t19+dq1.*t2.*t3.*t4.*3.0+I.*dq1.*m.*t2.*2.0+I.*dq1.*m.*t3.*2.0-I.*d.*dq1.*l.*m.*3.0-d.*dq1.*l.*t2.*t4.*3.0-d.*dq1.*l.*t3.*t4+dq2.*t2.*t3.*t4.*t6-dq1.*t2.*t3.*t4.*t14-I.*d.*dq2.*l.*m.*t6-d.*dq2.*l.*t2.*t4.*t6+d.*dq1.*l.*t3.*t4.*t14).*2.0;
end
