function [U,T] = autoGen_energy(q1,q2,dq1,dq2,m1,m2,g,l)
%AUTOGEN_ENERGY
%    [U,T] = AUTOGEN_ENERGY(Q1,Q2,DQ1,DQ2,M1,M2,G,L)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    17-Jun-2015 22:13:36

t2 = cos(q1);
t3 = dq1.^2;
t4 = l.^2;
t5 = sin(q1);
t6 = cos(q2);
U = -g.*m2.*(l.*t2+l.*t6)-g.*l.*m1.*t2;
if nargout > 1
    t7 = dq1.*l.*t2+dq2.*l.*t6;
    t8 = dq2.*l.*sin(q2)+dq1.*l.*t5;
    T = m1.*(t2.^2.*t3.*t4+t3.*t4.*t5.^2).*(1.0./2.0)+m2.*(t7.^2+t8.^2).*(1.0./2.0);
end
