function [P5,dP5] = autoGen_swingFootKinematics(q1,q2,q4,q5,dq1,dq2,dq4,dq5,l1,l2,l4,l5)
%AUTOGEN_SWINGFOOTKINEMATICS
%    [P5,DP5] = AUTOGEN_SWINGFOOTKINEMATICS(Q1,Q2,Q4,Q5,DQ1,DQ2,DQ4,DQ5,L1,L2,L4,L5)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    24-Sep-2015 12:04:44

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q4);
t5 = cos(q5);
t6 = sin(q1);
t7 = sin(q2);
t8 = sin(q4);
t9 = sin(q5);
P5 = [-l1.*t6-l2.*t7+l4.*t8+l5.*t9;l1.*t2+l2.*t3-l4.*t4-l5.*t5];
if nargout > 1
    dP5 = [-dq1.*l1.*t2-dq2.*l2.*t3+dq4.*l4.*t4+dq5.*l5.*t5;-dq1.*l1.*t6-dq2.*l2.*t7+dq4.*l4.*t8+dq5.*l5.*t9];
end
