function [f,fz,fzi] = autoGen_obj_powerSquared(dq1,dq2,dq3,dq4,dq5,u1,u2,u3,u4,u5)
%AUTOGEN_OBJ_POWERSQUARED
%    [F,FZ,FZI] = AUTOGEN_OBJ_POWERSQUARED(DQ1,DQ2,DQ3,DQ4,DQ5,U1,U2,U3,U4,U5)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    29-Sep-2015 09:22:18

t2 = dq1-dq2;
t3 = dq2-dq3;
t4 = dq3-dq4;
t5 = dq4-dq5;
t6 = u2.^2;
t7 = u1.^2;
t8 = dq1.*2.0;
t9 = dq2.*2.0;
t10 = t8-t9;
t11 = t6.*t10;
t12 = u3.^2;
t13 = dq3.*2.0;
t14 = t9-t13;
t15 = t12.*t14;
t16 = u4.^2;
t17 = dq4.*2.0;
t18 = t13-t17;
t19 = t16.*t18;
t20 = u5.^2;
t21 = dq5.*2.0;
t22 = t17-t21;
t23 = t20.*t22;
t24 = dq1.^2;
t25 = t2.^2;
t26 = t3.^2;
t27 = t4.^2;
t28 = t5.^2;
f = t6.*t25+t7.*t24+t12.*t26+t16.*t27+t20.*t28;
if nargout > 1
    fz = [t11+dq1.*t7.*2.0;-t11+t15;-t15+t19;-t19+t23;-t23;t24.*u1.*2.0;t25.*u2.*2.0;t26.*u3.*2.0;t27.*u4.*2.0;t28.*u5.*2.0];
end
if nargout > 2
    fzi = [7.0;8.0;9.0;1.0e1;1.1e1;1.2e1;1.3e1;1.4e1;1.5e1;1.6e1];
end
