function [f,fz,fzi] = autoGen_obj_costOfTransport(dq1,dq2,dq3,dq4,dq5,u1,u2,u3,u4,u5,m1,m2,m3,m4,m5,g,alpha,stepLength)
%AUTOGEN_OBJ_COSTOFTRANSPORT
%    [F,FZ,FZI] = AUTOGEN_OBJ_COSTOFTRANSPORT(DQ1,DQ2,DQ3,DQ4,DQ5,U1,U2,U3,U4,U5,M1,M2,M3,M4,M5,G,ALPHA,STEPLENGTH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    29-Sep-2015 09:22:17

t2 = dq1-dq2;
t3 = alpha.^2;
t4 = dq2-dq3;
t5 = dq3-dq4;
t6 = dq4-dq5;
t7 = 1.0./g;
t8 = 1.0./stepLength;
t9 = u1.^2;
t10 = dq1.^2;
t11 = t9.*t10;
t12 = t3+t11;
t13 = u2.^2;
t14 = t2.^2;
t15 = t13.*t14;
t16 = t3+t15;
t17 = m1+m2+m3+m4+m5;
t18 = 1.0./t17;
t19 = 1.0./sqrt(t16);
t20 = t2.*t13.*t19;
t21 = u3.^2;
t22 = t4.^2;
t23 = t21.*t22;
t24 = t3+t23;
t25 = 1.0./sqrt(t24);
t26 = u4.^2;
t27 = t5.^2;
t28 = t26.*t27;
t29 = t3+t28;
t30 = 1.0./sqrt(t29);
t31 = u5.^2;
t32 = t6.^2;
t33 = t31.*t32;
t34 = t3+t33;
f = t7.*t8.*t18.*(sqrt(t12)+sqrt(t16)+sqrt(t24)+sqrt(t29)+sqrt(t34));
if nargout > 1
    t35 = 1.0./sqrt(t34);
    t36 = dq4.*2.0;
    t37 = dq5.*2.0;
    t38 = t36-t37;
    t39 = 1.0./sqrt(t12);
    fz = [t7.*t8.*t18.*(t20+dq1.*t9.*t39);-t7.*t8.*t18.*(t20-t21.*t25.*(dq2.*2.0-dq3.*2.0).*(1.0./2.0));t7.*t8.*t18.*(t26.*t30.*(dq3.*2.0-dq4.*2.0).*(1.0./2.0)-t4.*t21.*t25);-t7.*t8.*t18.*(t5.*t26.*t30-t31.*t35.*t38.*(1.0./2.0));t7.*t8.*t18.*t31.*t35.*t38.*(-1.0./2.0);t7.*t8.*t10.*t18.*t39.*u1;t7.*t8.*t14.*t18.*t19.*u2;t7.*t8.*t18.*t22.*t25.*u3;t7.*t8.*t18.*t27.*t30.*u4;t7.*t8.*t18.*t32.*t35.*u5];
end
if nargout > 2
    fzi = [7.0;8.0;9.0;1.0e1;1.1e1;1.2e1;1.3e1;1.4e1;1.5e1;1.6e1];
end
