function dGvec = autoGen_comVel(q1,q2,q3,q4,q5,dq1,dq2,dq3,dq4,dq5,l1,l2,l3,l4,c1,c2,c3,c4,c5)
%AUTOGEN_COMVEL
%    DGVEC = AUTOGEN_COMVEL(Q1,Q2,Q3,Q4,Q5,DQ1,DQ2,DQ3,DQ4,DQ5,L1,L2,L3,L4,C1,C2,C3,C4,C5)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    24-Sep-2015 14:40:49

t2 = cos(q1);
t3 = sin(q1);
t4 = cos(q2);
t5 = sin(q2);
t6 = cos(q3);
t7 = sin(q3);
t8 = cos(q4);
t9 = sin(q4);
dGvec = [dq1.*(c1.*t2-l1.*t2);dq1.*(c1.*t3-l1.*t3);dq2.*(c2.*t4-l2.*t4)-dq1.*l1.*t2;dq2.*(c2.*t5-l2.*t5)-dq1.*l1.*t3;dq3.*(c3.*t6-l3.*t6)-dq1.*l1.*t2-dq2.*l2.*t4;dq3.*(c3.*t7-l3.*t7)-dq1.*l1.*t3-dq2.*l2.*t5;c4.*dq4.*t8-dq1.*l1.*t2-dq2.*l2.*t4;c4.*dq4.*t9-dq1.*l1.*t3-dq2.*l2.*t5;-dq1.*l1.*t2-dq2.*l2.*t4+dq4.*l4.*t8+c5.*dq5.*cos(q5);c5.*dq5.*sin(q5)-dq1.*l1.*t3-dq2.*l2.*t5+dq4.*l4.*t9];
