function G = autoGen_comPos(q1,q2,q3,q4,q5,m1,m2,m3,m4,m5,l1,l2,l3,l4,c1,c2,c3,c4,c5)
%AUTOGEN_COMPOS
%    G = AUTOGEN_COMPOS(Q1,Q2,Q3,Q4,Q5,M1,M2,M3,M4,M5,L1,L2,L3,L4,C1,C2,C3,C4,C5)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    22-Sep-2015 12:22:52

t2 = sin(q2);
t3 = sin(q1);
t4 = l1.*t3;
t5 = l2.*t2;
t6 = sin(q3);
t7 = sin(q4);
t8 = cos(q2);
t9 = cos(q1);
t10 = l1.*t9;
t11 = l2.*t8;
t12 = cos(q3);
t13 = cos(q4);
t14 = m1+m2+m3+m4+m5;
t15 = 1.0./t14;
G = [-t15.*(m2.*(t4+t5-c2.*t2)+m4.*(t4+t5-c4.*t7)+m3.*(t4+t5-c3.*t6+l3.*t6)+m1.*(t4-c1.*t3)+m5.*(t4+t5-l4.*t7-c5.*sin(q5)));t15.*(m2.*(t10+t11-c2.*t8)+m4.*(t10+t11-c4.*t13)+m3.*(t10+t11-c3.*t12+l3.*t12)+m1.*(t10-c1.*t9)+m5.*(t10+t11-l4.*t13-c5.*cos(q5)))];
