function [f,fz,fzi] = autoGen_obj_torqueSquared(u1,u2,u3,u4,u5)
%AUTOGEN_OBJ_TORQUESQUARED
%    [F,FZ,FZI] = AUTOGEN_OBJ_TORQUESQUARED(U1,U2,U3,U4,U5)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    22-Oct-2015 19:13:53

f = u1.^2+u2.^2+u3.^2+u4.^2+u5.^2;
if nargout > 1
    fz = [u1.*2.0;u2.*2.0;u3.*2.0;u4.*2.0;u5.*2.0];
end
if nargout > 2
    fzi = [1.2e1;1.3e1;1.4e1;1.5e1;1.6e1];
end
