function [ceq,ceqJac] = autoGen_cst_steplength(q1m,q2m,q4m,q5m,l1,l2,l4,l5,stepLength)
%AUTOGEN_CST_STEPLENGTH
%    [CEQ,CEQJAC] = AUTOGEN_CST_STEPLENGTH(Q1M,Q2M,Q4M,Q5M,L1,L2,L4,L5,STEPLENGTH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    24-Sep-2015 18:35:12

t2 = sin(q1m);
t3 = sin(q2m);
t4 = sin(q4m);
t5 = l4.*t4;
t6 = sin(q5m);
t7 = l5.*t6;
ceq = [-stepLength+t5+t7-l1.*t2-l2.*t3;t5+t7-l1.*t2-l2.*t3];
if nargout > 1
    t8 = cos(q1m);
    t9 = cos(q2m);
    t10 = cos(q4m);
    t11 = l4.*t10;
    t12 = cos(q5m);
    t13 = l5.*t12;
    ceqJac = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-l1.*t8,-l1.*t8,-l2.*t9,-l2.*t9,0.0,0.0,t11,t11,t13,t13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2, 22]);
end
