function [C,Cz] = autoGen_objective(t,q,dq,u,m,g,l,c,empty)
%AUTOGEN_OBJECTIVE
%    [C,CZ] = AUTOGEN_OBJECTIVE(T,Q,DQ,U,M,G,L,C,EMPTY)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    23-Sep-2015 15:01:27

t2 = u.^2;
t3 = sin(t);
t4 = t3+1.0;
C = empty+cos(q)+t2.*t4+dq.^2;
if nargout > 1
    Cz = [empty+t2.*cos(t);empty-sin(q);dq.*2.0+empty;empty+t4.*u.*2.0];
end
