function [C,Cz] = autoGen_objective(t,q,dq,u,m,g,l,c,empty)
%AUTOGEN_OBJECTIVE
%    [C,CZ] = AUTOGEN_OBJECTIVE(T,Q,DQ,U,M,G,L,C,EMPTY)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    23-Sep-2015 12:09:08

C = empty+u.^2;
if nargout > 1
    Cz = [empty;empty;empty;empty+u.*2.0];
end
