function [y,yz,yzi] = autoGen_cst_swingFootHeight(q1,q2,q4,q5,l1,l2,l4,l5,stepLength,stepHeight)
%AUTOGEN_CST_SWINGFOOTHEIGHT
%    [Y,YZ,YZI] = AUTOGEN_CST_SWINGFOOTHEIGHT(Q1,Q2,Q4,Q5,L1,L2,L4,L5,STEPLENGTH,STEPHEIGHT)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-Oct-2015 18:36:31

t3 = sin(q1);
t4 = l1.*t3;
t7 = sin(q2);
t8 = l2.*t7;
t9 = sin(q4);
t10 = l4.*t9;
t11 = sin(q5);
t12 = l5.*t11;
t2 = t4+t8-t10-t12;
t5 = 1.0./stepLength.^2;
t6 = cos(q1);
t13 = cos(q2);
t14 = cos(q4);
t15 = cos(q5);
y = -l1.*t6-l2.*t13+l4.*t14+l5.*t15-stepHeight.*(t2.^2.*t5-1.0);
if nargout > 1
    yz = [t4-l1.*stepHeight.*t2.*t5.*t6.*2.0;t8-l2.*stepHeight.*t2.*t5.*t13.*2.0;-t10+l4.*stepHeight.*t2.*t5.*t14.*2.0;-t12+l5.*stepHeight.*t2.*t5.*t15.*2.0];
end
if nargout > 2
    yzi = [2.0;3.0;5.0;6.0];
end
