function [f,fz,fzi] = autoGen_obj_costOfTransport(m1,m2,m3,m4,m5,u1,u2,u3,u4,u5,du1,du2,du3,du4,du5,sn1,sn2,sn3,sn4,sn5,sp1,sp2,sp3,sp4,sp5,g,stepLength,gammaNeg,gammaPos,alpha,beta,empty)
%AUTOGEN_OBJ_COSTOFTRANSPORT
%    [F,FZ,FZI] = AUTOGEN_OBJ_COSTOFTRANSPORT(M1,M2,M3,M4,M5,U1,U2,U3,U4,U5,DU1,DU2,DU3,DU4,DU5,SN1,SN2,SN3,SN4,SN5,SP1,SP2,SP3,SP4,SP5,G,STEPLENGTH,GAMMANEG,GAMMAPOS,ALPHA,BETA,EMPTY)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-Oct-2015 18:36:30

t2 = 1.0./g;
t3 = 1.0./stepLength;
t4 = m1+m2+m3+m4+m5;
t5 = 1.0./t4;
f = alpha.*(u1.^2+u2.^2+u3.^2+u4.^2+u5.^2)+beta.*(du1.^2+du2.^2+du3.^2+du4.^2+du5.^2)+t2.*t3.*t5.*(gammaNeg.*(sn1+sn2+sn3+sn4+sn5)+gammaPos.*(sp1+sp2+sp3+sp4+sp5));
if nargout > 1
    t6 = gammaNeg.*t2.*t3.*t5;
    t7 = empty+t6;
    t8 = gammaPos.*t2.*t3.*t5;
    t9 = empty+t8;
    fz = [alpha.*u1.*2.0;alpha.*u2.*2.0;alpha.*u3.*2.0;alpha.*u4.*2.0;alpha.*u5.*2.0;beta.*du1.*2.0;beta.*du2.*2.0;beta.*du3.*2.0;beta.*du4.*2.0;beta.*du5.*2.0;t7;t7;t7;t7;t7;t9;t9;t9;t9;t9];
end
if nargout > 2
    fzi = [1.2e1;1.3e1;1.4e1;1.5e1;1.6e1;1.7e1;1.8e1;1.9e1;2.0e1;2.1e1;2.2e1;2.3e1;2.4e1;2.5e1;2.6e1;2.7e1;2.8e1;2.9e1;3.0e1;3.1e1];
end
