function [c,cz,czi] = autoGen_cst_costOfTransport(dq1,dq2,dq3,dq4,dq5,u1,u2,u3,u4,u5,sn1,sn2,sn3,sn4,sn5,sp1,sp2,sp3,sp4,sp5,empty)
%AUTOGEN_CST_COSTOFTRANSPORT
%    [C,CZ,CZI] = AUTOGEN_CST_COSTOFTRANSPORT(DQ1,DQ2,DQ3,DQ4,DQ5,U1,U2,U3,U4,U5,SN1,SN2,SN3,SN4,SN5,SP1,SP2,SP3,SP4,SP5,EMPTY)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-Oct-2015 18:36:28

c = [sn1-sp1+dq1.*u1;sn2-sp2-u2.*(dq1-dq2);sn3-sp3-u3.*(dq2-dq3);sn4-sp4-u4.*(dq3-dq4);sn5-sp5-u5.*(dq4-dq5)];
if nargout > 1
    t2 = empty+1.0;
    t3 = empty-1.0;
    cz = [u1;-u2;u2;-u3;u3;-u4;u4;-u5;u5;dq1;-dq1+dq2;-dq2+dq3;-dq3+dq4;-dq4+dq5;t2;t2;t2;t2;t2;t3;t3;t3;t3;t3];
end
if nargout > 2
    czi = [3.1e1;3.2e1;3.7e1;3.8e1;4.3e1;4.4e1;4.9e1;5.0e1;5.5e1;5.6e1;6.2e1;6.8e1;7.4e1;8.0e1;1.06e2;1.12e2;1.18e2;1.24e2;1.3e2;1.31e2;1.37e2;1.43e2;1.49e2;1.55e2];
end
