function [f,fz,fzi] = autoGen_obj_costOfTransport(m1,m2,m3,m4,m5,u1,u2,u3,u4,u5,sn1,sn2,sn3,sn4,sn5,sp1,sp2,sp3,sp4,sp5,g,stepLength,alpha,empty)
%AUTOGEN_OBJ_COSTOFTRANSPORT
%    [F,FZ,FZI] = AUTOGEN_OBJ_COSTOFTRANSPORT(M1,M2,M3,M4,M5,U1,U2,U3,U4,U5,SN1,SN2,SN3,SN4,SN5,SP1,SP2,SP3,SP4,SP5,G,STEPLENGTH,ALPHA,EMPTY)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    24-Oct-2015 18:12:49

t2 = 1.0./g;
t3 = 1.0./stepLength;
t4 = m1+m2+m3+m4+m5;
t5 = 1.0./t4;
f = alpha.*(u1.^2+u2.^2+u3.^2+u4.^2+u5.^2)+t2.*t3.*t5.*(sn1+sn2+sn3+sn4+sn5+sp1+sp2+sp3+sp4+sp5);
if nargout > 1
    t6 = t2.*t3.*t5;
    t7 = empty+t6;
    fz = [alpha.*u1.*2.0;alpha.*u2.*2.0;alpha.*u3.*2.0;alpha.*u4.*2.0;alpha.*u5.*2.0;t7;t7;t7;t7;t7;t7;t7;t7;t7;t7];
end
if nargout > 2
    fzi = [1.2e1;1.3e1;1.4e1;1.5e1;1.6e1;1.7e1;1.8e1;1.9e1;2.0e1;2.1e1;2.2e1;2.3e1;2.4e1;2.5e1;2.6e1];
end
